---
# tasks/validate_prerequisites.yml
- name: "Validar servidores definidos"
  ansible.builtin.assert:
    that:
      - file_sync_source_server is defined
      - file_sync_source_server | length > 0
      - file_sync_target_server is defined
      - file_sync_target_server | length > 0
      - file_sync_source_server != file_sync_target_server
    fail_msg: "Servidores origen y destino deben estar definidos y ser diferentes"
    success_msg: "OK: Servidores validados {{ file_sync_source_server }} → {{ file_sync_target_server }}"

- name: "Verificar conectividad a servidor origen"
  ansible.windows.win_ping:
  register: source_connectivity

- name: "Verificar conectividad a servidor destino"
  ansible.windows.win_ping:
  delegate_to: "{{ file_sync_target_server }}"
  register: target_connectivity

- name: "Validar ruta origen"
  ansible.windows.win_stat:
    path: "{{ file_sync_comparison_path }}"
  register: source_path_check

- name: "Verificar ruta origen existe"
  ansible.builtin.assert:
    that:
      - source_path_check.stat.exists
      - source_path_check.stat.isdir
    fail_msg: "Ruta {{ file_sync_comparison_path }} no existe en servidor origen {{ file_sync_source_server }}"
    success_msg: "OK: Ruta origen validada en {{ file_sync_source_server }}"

- name: "Validar ruta destino"
  ansible.windows.win_stat:
    path: "{{ file_sync_comparison_path }}"
  delegate_to: "{{ file_sync_target_server }}"
  register: target_path_check

- name: "Verificar ruta destino existe"
  ansible.builtin.assert:
    that:
      - target_path_check.stat.exists
      - target_path_check.stat.isdir
    fail_msg: "Ruta {{ file_sync_comparison_path }} no existe en servidor destino {{ file_sync_target_server }}"
    success_msg: "OK: Ruta destino validada en {{ file_sync_target_server }}"

- name: "Mostrar resumen de validación"
  ansible.builtin.debug:
    msg:
      - "════════════════════════════════════════════"
      - "VALIDACIÓN COMPLETADA"
      - "════════════════════════════════════════════"
      - "Origen: {{ file_sync_source_server }}"
      - "Destino: {{ file_sync_target_server }}"
      - "Ruta: {{ file_sync_comparison_path }}"
      - "Conectividad Origen: OK"
      - "Conectividad Destino: OK"
      - "════════════════════════════════════════════"
